Android: Changed to select raw image quality when using localhost(127.0.0.1)
bk138/multivnc pull request #113
Opened 2021-01-24 07:37 UTC by nagasawa

Please make sure you've read and understood the [contribution guidelines](../CONTRIBUTING.md).

Fixes #102 .

Changes proposed in this pull request:

*Android: Changed to select raw image quality when using localhost(127.0.0.1)

2021-01-24 13:44 UTC, bk138 requested changes
Thank you very much! Some changes needed, also please make the commit message (as noted in CONTRIBUTING.md):

* shorter
* have a wording  so the sentence "when applied, this commit will ..." applies

2021-01-24 13:44 UTC, bk138 commented on android/app/src/main/cpp/vncconn.c
> +}
please remove unrelated changes

2021-01-24 13:44 UTC, bk138 commented on android/app/src/main/cpp/vncconn.c
> +    else
please leave the non-localhost case to the library's default. i.e. remove the else branch.

2021-01-24 13:44 UTC, bk138 commented on android/app/src/main/cpp/vncconn.c
> +    if (0 == strcmp("localhost", cl->serverHost) || 0 == strcmp("127.0.0.1", cl->serverHost))
* style: please put the 0 as second place in the comparison
* logic: please also handle the IPv6 case.

2021-01-27 11:50 UTC, bk138 commented
@nagasawa any news on this?

2021-01-27 16:50 UTC, nagasawa commented
I'm sorry, but I'm working on weekdays and I don't have enough time, so I have to deal with Saturdays and Sundays.

2021-01-30 01:39 UTC, nagasawa-umebius commented
dce10b8

I've committed the fix.
I couldn't fix it because I don't know why the change appears on the last line.

2021-01-30 10:03 UTC, closed without merging

2021-01-30 10:04 UTC, bk138 commented
I've taken the freedom to modify your changes as proposed and use a proper commit message via 208b86a3ed3630edbd8eba12786c92d96eb66079.